name: Release unitscan
on:
  workflow_dispatch:
permissions:
  contents: write
  actions: read
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Extract version from TOC file
        id: get_version
        run: |
          echo "version=1.1" >> $GITHUB_OUTPUT
          echo "Found version: $VERSION"
      
      - name: Create unitscan zip
        run: |
          mkdir unitscan
          rsync -av --exclude='.git' --exclude='.github' --exclude='*.md' --exclude='LICENSE' --exclude='.gitattributes' --exclude='unitscan' . unitscan/
          zip -r unitscan.zip unitscan/
      
      - name: Create Versioned Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: unitscan-v${{ steps.get_version.outputs.version }}
          name: unitscan v${{ steps.get_version.outputs.version }}
          files: unitscan.zip
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
